
server:
  port: 3344

spring:
  application:
    name:  microservicecloud-configService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ffati/microservicecloud-configService-test.git

#测试与git通信 http://localhost:3344/application-dev.yml
# 访问地址一：http://localhost:3344/neo-config/dev
# 访问地址二：http://localhost:3344/neo-config-dev.properties


